---

#
# Create folder for portainer_agent
- name: Create folder for portainer_agent
  file:
    path: /usr/local/bin/portainer_agent
    state: directory
    mode: '0755'


#
# Create data-folder for portainer_agent
- name: Create data-folder for portainer_agent
  file:
    path: /usr/local/bin/portainer_agent/data
    state: directory
    mode: '0755'


#
# Create docker-compose
- name: Create docker-compose
  template:
    src: docker-compose.yaml.j2
    dest: /usr/local/bin/portainer_agent/docker-compose.yaml


#
# Start with docker-compose
- name: Start with docker-compose
  shell:
    cmd: docker-compose up -d
    chdir: /usr/local/bin/portainer_agent/
